# Generated by Django 2.2.28 on 2023-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('attributes', models.TextField()),
                ('is_favorite', models.BooleanField(default='False')),
                ('description', models.TextField()),
                ('date_adopted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
